apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: htping-service
  labels:
    k8s-app: htping-service
  namespace: htping
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: htping-service
  template:
    metadata:
      labels:
        k8s-app: htping-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: htping
        image: uubk/htping:latest
        args: ["-name=new"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: htping-service
  labels:
    k8s-app: htping-service
  namespace: htping
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: htping-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-htping-service
  namespace: htping
spec:
  rules:
  - host: htping-b.vis.ethz.ch
    http:
      paths:
      - backend:
          serviceName: htping-service
          servicePort: 80
        path: /
  - host: htping.vis.ethz.ch
    http:
      paths:
      - backend:
          serviceName: htping-service
          servicePort: 80
        path: /
